### PR TITLE
Add infrastructure for bibliography management

### PR DESCRIPTION
**Pull request by andrenmelo**

### CODE REVIEW

**Comment by andrenmelo** [comment]
@akhmerov mind taking a looking and then merging if it looks good?

**Comment by akhmerov** [comment]
I'll try closing and opening to see if pre-commit CI works.

**Comment by akhmerov** [comment]
@andrenmelo see https://results.pre-commit.ci/run/github/440568287/1642159645.ktvlq1RFSdmBys-C3NzdXg

**Comment by akhmerov** [comment]
OK, so the problem is that the pre-commit configuration of the local hook isn't right (you can confirm this by seeing that precommit fails to execute the code). If we use a local hook we should specify which package needs to be installed.

**Review by akhmerov — APPROVED** [review]

**Pull request merged**
