### PR TITLE
create an umbrella page

### PR DESCRIPTION
**Pull request by akhmerov**
So far only created the scaffolding, we should expand the bibliography and add  descriptions

### CODE REVIEW

**Comment by akhmerov** [comment]
Update summary (CC @vfatemi): we wrote some words to introduce each different limit as well as why the different perspectives make sense

**Comment by vfatemi** [comment]
A few questions on the minimal models page: 

- [ ] first bold text: what do we mean exactly by "in metallic regions"? 
- [ ] Also, a dot coupled to a normal metal also does not have a quantized charge, although it is incoherent. Contrast to this might be good. 
- [ ] a bit awkward to refer to "removing quasiparticles from the vacuum state". I know what you mean, but probably we can improve the phrasing. 

Otherwise, the first minimal model looks good. 

Thinking on the long junction case, I think it would be instructive and helpful to aim for plotting the wavefunctions long Andreev dot (with no backscattering) and compare with the long normal dot.

**Comment by akhmerov** [comment]
Indeed. I imagine it'd go well as a part of the scattering descriptions. Or do you have something else in mind?

**Comment by andrenmelo** [comment]
> Indeed. I imagine it'd go well as a part of the scattering descriptions. Or do you have something else in mind?

Yup. I was thinking we could even use some collapsable jupyter-book elements to avoid breaking the flow.

**Comment by akhmerov** [comment]
What's still pending after our round of edits?

**Comment by andrenmelo** [comment]
> What's still pending after our round of edits?

Just needed to change notation in the quantum dot model section. I also polished that subsection a bit more. I'm fine with the merge now.

**Pull request merged**
